version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=dataservicex
      - MYSQL_USER=dataservicex
      - MYSQL_PASSWORD=dataservicex
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"